-- ============================================================
-- Seed Data: Products + Promo Codes
-- Auto-generated from products.json and constants/index.ts
-- Run: node supabase/generate-seed.js
-- ============================================================

-- Clear existing seed data (idempotent)
truncate public.products cascade;
truncate public.promo_codes cascade;

-- ============================================================
-- Products
-- ============================================================

-- ID Card & Lanyard
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (8, 'Paket IDC LYD 2S', 'paket-idc-lyd-2s', '/product-image/paket-idc-2s.webp', '{}', 'Paket lengkap dengan ID card dua sisi dan lanyard yang sesuai.', 25000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":25000},{"minQuantity":4,"price":23000},{"minQuantity":25,"price":20000},{"minQuantity":100,"price":17000}]'::jsonb, '2-3 hari', 4.9, true, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 1);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (9, 'Paket IDC LYD Kulit', 'paket-idc-lyd-kulit', '/product-image/paket-idc-case-kulit.webp', ARRAY['/product-image/case-kulit.webp']::text[], 'Paket premium dengan ID card, case kulit, dan lanyard yang sesuai.', 30000, 28000, 'ID Card & Lanyard', '[{"minQuantity":1,"price":28000},{"minQuantity":4,"price":27000},{"minQuantity":25,"price":26500},{"minQuantity":100,"price":25000}]'::jsonb, '3-4 hari', 5, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 2);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (10, 'Paket IDC LYD Premium', 'paket-idc-lyd-premium', '/product-image/paket-idc-lyd-premium.webp', ARRAY['/product-image/case-premium.webp']::text[], 'Paket deluxe dengan ID card dua sisi, case premium, dan lanyard custom.', 30000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":30000},{"minQuantity":4,"price":28000},{"minQuantity":25,"price":26000},{"minQuantity":100,"price":24000}]'::jsonb, '3-5 hari', 4.9, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 3);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (7, 'Paket IDC LYD 1S', 'paket-idc-lyd-1s', '/product-image/paket-idc-1s.webp', '{}', 'Paket lengkap dengan ID card satu sisi dan lanyard yang sesuai.', 20000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":20000},{"minQuantity":4,"price":18000},{"minQuantity":25,"price":16000},{"minQuantity":100,"price":14000}]'::jsonb, '2-3 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 4);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (3, 'IDC Tali & Case Kulit', 'idc-tali-case-kulit', '/product-image/case-tali-kulit.webp', ARRAY['/product-image/case-kulit.webp']::text[], 'ID card premium dengan case kulit dan tali lanyard.', 30000, 28000, 'ID Card & Lanyard', '[{"minQuantity":1,"price":28000},{"minQuantity":4,"price":27000},{"minQuantity":25,"price":26500},{"minQuantity":100,"price":25000}]'::jsonb, '3-5 hari', 4.9, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 5);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (2, 'ID Card 2S', 'id-card-2s', '/product-image/ID Card 2S.webp', ARRAY['/product-image/Case-ID Card.webp']::text[], 'ID card dua sisi dengan bahan premium berkualitas.', 10000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":10000},{"minQuantity":4,"price":9000},{"minQuantity":25,"price":8000},{"minQuantity":100,"price":7000}]'::jsonb, '2-3 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 6);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (1, 'ID Card 1S', 'id-card-1s', '/product-image/ID Card 1S.webp', ARRAY['/product-image/Case-ID Card.webp']::text[], 'ID card satu sisi dengan bahan premium berkualitas.', 9000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":9000},{"minQuantity":4,"price":8000},{"minQuantity":25,"price":7000},{"minQuantity":100,"price":6000}]'::jsonb, '1-2 hari', 4.7, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 7);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (4, 'Lanyard Saja 1S', 'lanyard-saja-1s', '/product-image/lanyard-only-1S.webp', ARRAY['/product-image/lanyard-only-1S-2.webp']::text[], 'Lanyard cetak satu sisi tanpa ID card atau case.', 15000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":15000},{"minQuantity":4,"price":13000},{"minQuantity":25,"price":12000},{"minQuantity":100,"price":10000}]'::jsonb, '1-2 hari', 4.6, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 8);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (5, 'Lanyard Saja 2S', 'lanyard-saja-2s', '/product-image/lanyard-only-2S.webp', ARRAY['/product-image/lanyard-only-2S-2.webp']::text[], 'Lanyard cetak dua sisi tanpa ID card atau case.', 17000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":17000},{"minQuantity":4,"price":16000},{"minQuantity":25,"price":15000},{"minQuantity":100,"price":13000}]'::jsonb, '1-2 hari', 4.7, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 9);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (6, 'IDC Tali Biasa', 'idc-tali-biasa', '/product-image/IDC Tali Biasa.webp', ARRAY['/product-image/case-biasa.webp']::text[], 'ID card standar dengan lanyard biasa.', 13000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":13000},{"minQuantity":4,"price":12000},{"minQuantity":25,"price":10000},{"minQuantity":100,"price":8000}]'::jsonb, '1-2 hari', 4.5, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 10);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (24, 'IDC Lanyard tali Hitam Polos', 'idc-lanyard-tali-hitam-polos', '/product-image/IDC-Tali Hitam.webp', '{}', 'ID card dengan lanyard tali hitam polos, praktis dan elegan.', 14000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":14000},{"minQuantity":50,"price":13000}]'::jsonb, '1-2 hari', 4.6, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 11);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (25, 'IDC B4 Lanyard Hitam Polos', 'idc-b4-lanyard-hitam-polos', '/product-image/IDC B4 Lanyard Hitam Polos.webp', '{}', 'ID Card kertas dengan ukuran B4 (15.5 × 16.6 cm), tali hitam polos', 7000, 5000, 'ID Card & Lanyard', '[{"minQuantity":1,"price":5000}]'::jsonb, '1-2 hari', 4.5, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 12);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (26, 'ID Card Yoyo (Tanpa Stiker)', 'id-card-yoyo-tanpa-stiker', '/product-image/New Product/IDC-YOYO-REG.webp', '{}', 'ID card yoyo praktis. Ready stok berbagai warna.', 20000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":20000},{"minQuantity":10,"price":15000}]'::jsonb, '1-2 hari', 4.7, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 13);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (27, 'Stiker ID Card Yoyo Saja', 'stiker-id-card-yoyo-saja', '/product-image/New Product/IDC-YOYO-REG-STIKER.webp', ARRAY['/product-image/New Product/IDC-YOYO-PREM-AK-STIKER.webp', '/product-image/New Product/IDC-YOYO-PREM-SEMI-STIKER.webp']::text[], 'ID card yoyo custom dengan stiker logo Anda.', 10000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":10000}]'::jsonb, '2-3 hari', 4.7, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 14);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (28, 'ID Card Yoyo Premium Akrilik (Tanpa Stiker)', 'id-card-yoyo-premium-akrilik-tanpa-stiker', '/product-image/New Product/IDC-YOYO-PREM-AK.webp', '{}', 'Yoyo dengan case premium akrilik transparan.', 28000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":28000},{"minQuantity":10,"price":25000}]'::jsonb, '2-3 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 15);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (30, 'ID Card Yoyo Premium Semi Transparan (Tanpa Stiker)', 'id-card-yoyo-premium-semi-transparan-tanpa-stiker', '/product-image/New Product/IDC-YOYO-PREM-SEMI.webp', '{}', 'Yoyo premium dengan case semi transparan warna biru.', 25000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":25000},{"minQuantity":10,"price":23000}]'::jsonb, '2-3 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 16);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (34, 'Que Card', 'que-card', '/product-image/que-card.webp', '{}', 'Que Card dengan ukuran A5 ISO (14.8 x 21.0 cm), kualitas premium.', 15000, NULL, 'ID Card & Lanyard', '[{"minQuantity":1,"price":15000}]'::jsonb, '2-3 hari', 4.7, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 17);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (2200, 'Casing ID Card', 'casing-id-card', '/product-image/case-variant/case-reguler-color (black, white, semi transparent putih susu, ble, green, red, transparent).jpg', ARRAY['/product-image/case-variant/Case Bening.jpg', '/product-image/case-variant/case-leather kulit.jpg']::text[], 'Casing ID Card tersedia dalam berbagai jenis: Case Reguler Colorful, Case Bening Reguler, Case Putih Susu, Case Premium Bening, dan Case Kulit premium.', 2000, NULL, 'ID Card & Lanyard', '[]'::jsonb, 'Ready stock', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[{"code":"Case Reg Merah","image":"/product-image/case-variant/case-reguler-color (black, white, semi transparent putih susu, ble, green, red, transparent).jpg","price":2000},{"code":"Case Reg Hijau","image":"/product-image/case-variant/case-reguler-color (black, white, semi transparent putih susu, ble, green, red, transparent).jpg","price":2000},{"code":"Case Reg Biru","image":"/product-image/case-variant/case-reguler-color (black, white, semi transparent putih susu, ble, green, red, transparent).jpg","price":2000},{"code":"Case Reg Putih","image":"/product-image/case-variant/case-reguler-color (black, white, semi transparent putih susu, ble, green, red, transparent).jpg","price":2000},{"code":"Case Reg Kuning","image":"/product-image/case-variant/case-reguler-color (black, white, semi transparent putih susu, ble, green, red, transparent).jpg","price":2000},{"code":"Case Bening Reg","image":"/product-image/case-variant/Case Bening reg.jfif","price":2000},{"code":"Case Putih Susu","image":"/product-image/case-variant/Case Putih Susu.jfif","price":2000},{"code":"Case Premium","image":"/product-image/case-variant/Case Bening.jpg","price":7000},{"code":"Case Kulit","image":"/product-image/case-variant/case-leather kulit.jpg","price":5000}]'::jsonb, '[]'::jsonb, false, 18);

-- Media Promosi
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (11, 'Banner Indoor/Outdoor', 'banner-indooroutdoor', '/product-image/Banner 1.webp', ARRAY['/product-image/Banner 2.webp']::text[], 'Banner custom cetak untuk acara dan promosi.', 18000, NULL, 'Media Promosi', '[{"minQuantity":1,"price":18000},{"minQuantity":4,"price":18000},{"minQuantity":25,"price":17000},{"minQuantity":100,"price":16000}]'::jsonb, '3-5 hari', 4.8, false, 'm²', true, 'dimensional', 18000, 0.5, 5, 0.5, 10, '[]'::jsonb, '[]'::jsonb, false, 19);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (12, 'X Banner (60x160)', 'x-banner-60x160', '/product-image/X banner 1.webp', ARRAY['/product-image/X banner-2.webp']::text[], 'Stand banner bentuk X dengan banner cetak custom ukuran 60x160cm.', 90000, NULL, 'Media Promosi', '[{"minQuantity":1,"price":90000},{"minQuantity":4,"price":85000},{"minQuantity":25,"price":80000},{"minQuantity":100,"price":75000}]'::jsonb, '2-3 hari', 4.6, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 20);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (13, 'Roll Banner', 'roll-banner', '/product-image/Roll Banner 1.webp', ARRAY['/product-image/Roll Banner 2.webp']::text[], 'Banner gulung portable dengan stand, sempurna untuk acara dan pameran.', 350000, NULL, 'Media Promosi', '[{"minQuantity":1,"price":350000},{"minQuantity":4,"price":170000},{"minQuantity":25,"price":160000},{"minQuantity":100,"price":150000}]'::jsonb, '3-4 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 21);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (14, 'Poster A3', 'poster-a3', '/product-image/Poster 1.webp', ARRAY['/product-image/Poster 2.webp']::text[], 'Poster ukuran A3 dicetak pada kertas berkualitas tinggi.', 25000, NULL, 'Media Promosi', '[{"minQuantity":1,"price":25000},{"minQuantity":4,"price":22000},{"minQuantity":25,"price":20000},{"minQuantity":100,"price":18000}]'::jsonb, '1-2 hari', 4.7, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 22);

-- Merchandise
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (15, 'Cutting Stiker Kontur Chromo', 'cutting-stiker-kontur-chromo', '/product-image/Cut Stiker.webp', ARRAY['/product-image/cut-stiker1.webp']::text[], 'Stiker vinyl potong custom dengan desain Anda.', 15000, NULL, 'Merchandise', '[{"minQuantity":1,"price":15000},{"minQuantity":4,"price":12000},{"minQuantity":25,"price":10000},{"minQuantity":100,"price":8000}]'::jsonb, '1-2 hari', 4.6, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[{"type":"Laminasi Doff","price":0},{"type":"Laminasi Glossy","price":0},{"type":"Tanpa Laminasi","price":0}]'::jsonb, false, 23);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (32, 'Cutting Stiker Vinyl A3+', 'cutting-stiker-vinyl-a3', '/product-image/New Product/STIKER-VYNIL.webp', ARRAY['/product-image/New Product/STIKER-VYNIL-2.webp']::text[], 'Cetak stiker bahan vinyl berkualitas per lembar A3+.', 22000, NULL, 'Merchandise', '[{"minQuantity":1,"price":22000}]'::jsonb, '1-2 hari', 4.8, false, 'lembar', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 24);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (33, 'Cut Stiker Vynil Papan Bunga', 'cut-stiker-vynil-papan-bunga', '/product-image/vynilcut.webp', '{}', 'Jasa cutting stiker untuk papan bunga akrilik, desain dalam format CDR/JPG high resolution. Sudah termasuk Masking. Ukuran A3: 27.7 cm × 42 cm', 15000, NULL, 'Merchandise', '[{"minQuantity":1,"price":15000},{"minQuantity":4,"price":14000},{"minQuantity":25,"price":13000},{"minQuantity":100,"price":12000}]'::jsonb, '1-2 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 25);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (16, 'Ganci Akrilik', 'ganci-akrilik', '/product-image/ganciakrilik-1.webp', ARRAY['/product-image/ganciakrilik-2.webp', '/product-image/ganciakrilik-3.webp']::text[], 'Ganci akrilik custom cetak dengan desain Anda.', 8000, NULL, 'Merchandise', '[{"minQuantity":1,"price":8000},{"minQuantity":4,"price":7000},{"minQuantity":25,"price":6000},{"minQuantity":100,"price":5000}]'::jsonb, '1-2 hari', 4.5, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 26);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (17, 'Ganci 3 cm', 'ganci-3-cm', '/product-image/Ganci-3cm-1.webp', '{}', 'Ganci custom cetak diameter 3 cm.', 3000, NULL, 'Merchandise', '[{"minQuantity":1,"price":3000},{"minQuantity":4,"price":2700},{"minQuantity":25,"price":2500},{"minQuantity":100,"price":2300}]'::jsonb, '1-2 hari', 4.7, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 27);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (18, 'Ganci 5 cm', 'ganci-5-cm', '/product-image/Ganci-5-cm1.webp', '{}', 'Ganci custom cetak diameter 5 cm.', 5000, NULL, 'Merchandise', '[{"minQuantity":1,"price":5000},{"minQuantity":4,"price":4500},{"minQuantity":25,"price":4000},{"minQuantity":100,"price":3000}]'::jsonb, '1 hari', 4.6, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 28);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (19, 'Ganci Tali', 'ganci-tali', '/product-image/ganci-tali.webp', ARRAY['/product-image/ganci-tali-2.webp']::text[], 'Ganci custom cetak dengan tambahan tali.', 4000, NULL, 'Merchandise', '[]'::jsonb, '1-2 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[{"code":"1 Sisi","image":"/product-image/ganci-tali.webp","price":4000},{"code":"2 Sisi","image":"/product-image/ganci-tali.webp","price":5000}]'::jsonb, '[]'::jsonb, false, 29);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (103, 'Pin Kait Peniti 3 cm', 'pin-kait-peniti-3-cm', '/product-image/pin-3cm.webp', '{}', 'Pin kait peniti diameter 3 cm.', 3000, NULL, 'Merchandise', '[{"minQuantity":1,"price":3000}]'::jsonb, '1-2 hari', 4.7, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 30);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (104, 'Pin Kait Peniti 5 cm', 'pin-kait-peniti-5-cm', '/product-image/pin-5cm.webp', '{}', 'Pin kait peniti diameter 5 cm.', 5000, NULL, 'Merchandise', '[{"minQuantity":1,"price":5000}]'::jsonb, '1-2 hari', 4.7, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 31);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (20, 'Mug Custom', 'mug-custom', '/product-image/Mug 1.webp', ARRAY['/product-image/Mug 2.webp', '/product-image/Mug 3.webp']::text[], 'Mug keramik dengan desain cetak, aman untuk microwave dan mesin pencuci piring.', 28000, NULL, 'Merchandise', '[{"minQuantity":1,"price":28000},{"minQuantity":4,"price":25000},{"minQuantity":25,"price":22000},{"minQuantity":100,"price":19000}]'::jsonb, '3-5 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 32);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (21, 'Tumbler Custom', 'tumbler-custom', '/product-image/Insert Paper 1.webp', ARRAY['/product-image/Insert Paper 2.webp', '/product-image/Insert Paper 3.webp']::text[], 'Tumbler travel custom cetak dengan tutup, cocok untuk minuman panas dan dingin.', 28000, NULL, 'Merchandise', '[{"minQuantity":1,"price":28000},{"minQuantity":2,"price":25000},{"minQuantity":25,"price":23000},{"minQuantity":100,"price":20000}]'::jsonb, '3-5 hari', 4.9, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 33);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (22, 'Plakat Akrilik Reg', 'plakat-akrilik-reg', '/product-image/plakat/PKA 004.webp', ARRAY['/product-image/plakat-reg-1.webp', '/product-image/plakat-reg-2.webp', '/product-image/plakat-reg-3.webp', '/product-image/plakat/PKA 005.webp', '/product-image/plakat/PKA 006.webp', '/product-image/plakat/PKA 007.webp']::text[], 'Plakat akrilik berkualitas tinggi dengan berbagai pilihan model.', 90000, NULL, 'Merchandise', '[{"minQuantity":1,"price":90000}]'::jsonb, '3-5 hari', 4.9, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[{"code":"PKA004","image":"/product-image/plakat/PKA 004.jpg"},{"code":"PKA005","image":"/product-image/plakat/PKA 005.jpg"},{"code":"PKA006","image":"/product-image/plakat/PKA 006.jpg"},{"code":"PKA007","image":"/product-image/plakat/PKA 007.jpg"},{"code":"PKA008","image":"/product-image/plakat/PKA 008.jpg"},{"code":"PKA009","image":"/product-image/plakat/PKA 009.jpg"},{"code":"PKA010","image":"/product-image/plakat/PKA 010.jpg"},{"code":"PKA011","image":"/product-image/plakat/PKA 011.jpg"},{"code":"PKA012","image":"/product-image/plakat/PKA 012.jpg"}]'::jsonb, '[]'::jsonb, false, 34);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (2100, 'Plakat Akrilik UV', 'plakat-akrilik-uv', '/product-image/Merch/Plakat-UV/UV-1.webp', ARRAY['/product-image/Merch/Plakat-UV/UV-2.webp', '/product-image/Merch/Plakat-UV/UV-3.webp']::text[], 'Plakat Akrilik UV berkualitas tinggi dengan berbagai pilihan ketebalan. Sudah termasuk box bludru.', 125000, NULL, 'Merchandise', '[]'::jsonb, '3-5 hari', 4.9, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[{"code":"3 mm","image":"/product-image/Merch/Plakat-UV/UV-1.webp","price":125000},{"code":"5 mm","image":"/product-image/Merch/Plakat-UV/UV-1.webp","price":165000},{"code":"8 mm","image":"/product-image/Merch/Plakat-UV/UV-1.webp","price":190000},{"code":"10 mm","image":"/product-image/Merch/Plakat-UV/UV-1.webp","price":200000},{"code":"20 mm","image":"/product-image/Merch/Plakat-UV/UV-1.webp","price":285000}]'::jsonb, '[]'::jsonb, false, 35);

-- Papan Bunga
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (1001, 'Papan Bunga Kecil - Pink Purple Gradient #PKK1', 'papan-bunga-kecil-pink-purple-gradient-pkk1', '/product-image/papan-bunga/Kecil - KODE PKK1 - Pink Purple gradient dengan bunga dan kupu-kupu.webp', '{}', 'Papan bunga kecil dengan desain pink purple gradient, dilengkapi dengan bunga dan kupu-kupu.', 65000, NULL, 'Papan Bunga', '[{"minQuantity":1,"price":65000},{"minQuantity":3,"price":63000},{"minQuantity":5,"price":60000}]'::jsonb, '1-2 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 36);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (1002, 'Papan Bunga Kecil - Bunga Matahari Mini #PKK3', 'papan-bunga-kecil-bunga-matahari-mini-pkk3', '/product-image/papan-bunga/Kecil - KODE PKK3 dengan Bunga matahari mini dan anggrek putih.webp', '{}', 'Papan bunga kecil dengan bunga matahari mini dan anggrek putih.', 65000, NULL, 'Papan Bunga', '[{"minQuantity":1,"price":65000},{"minQuantity":3,"price":63000},{"minQuantity":5,"price":60000}]'::jsonb, '1-2 hari', 4.9, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 37);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (1003, 'Papan Bunga Kecil - Pink Gold Tropical #PKK5', 'papan-bunga-kecil-pink-gold-tropical-pkk5', '/product-image/papan-bunga/Kecil - KODE PKK5 - Pink gold tropical.webp', '{}', 'Papan bunga kecil dengan tema pink gold tropical.', 65000, NULL, 'Papan Bunga', '[{"minQuantity":1,"price":65000},{"minQuantity":3,"price":63000},{"minQuantity":5,"price":60000}]'::jsonb, '1-2 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 38);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (1004, 'Papan Bunga - Plakat Bunga Anggrek Biru #PKB2', 'papan-bunga-plakat-bunga-anggrek-biru-pkb2', '/product-image/papan-bunga/KODE PKB2 - Plakat Bunga dengan anggrek biru moonlight.webp', '{}', 'Plakat bunga dengan anggrek biru moonlight.', 70000, NULL, 'Papan Bunga', '[{"minQuantity":1,"price":70000},{"minQuantity":3,"price":68000},{"minQuantity":5,"price":65000}]'::jsonb, '1-2 hari', 4.9, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 39);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (1005, 'Papan Bunga - Plakat Bulat Anggrek Putih #PKB1', 'papan-bunga-plakat-bulat-anggrek-putih-pkb1', '/product-image/papan-bunga/KODE PKB1 - Plakat Bulat dengan bunga anggrek putih.webp', '{}', 'Plakat bulat dengan bunga anggrek putih.', 70000, NULL, 'Papan Bunga', '[{"minQuantity":1,"price":70000},{"minQuantity":3,"price":68000},{"minQuantity":5,"price":65000}]'::jsonb, '1-2 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 40);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (1006, 'Papan Bunga - Pink Mawar Love #PKK6', 'papan-bunga-pink-mawar-love-pkk6', '/product-image/papan-bunga/KODE PKK6 - Pink dengan bunga mawar dan love di tepi.webp', '{}', 'Papan bunga pink dengan bunga mawar dan love di tepi.', 70000, NULL, 'Papan Bunga', '[{"minQuantity":1,"price":70000},{"minQuantity":3,"price":68000},{"minQuantity":5,"price":65000}]'::jsonb, '1-2 hari', 4.9, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 41);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (1007, 'Papan Bunga - Hitam Emas Mewah #PKK7', 'papan-bunga-hitam-emas-mewah-pkk7', '/product-image/papan-bunga/KODE PKK7 plakat hitam emas mewah dengan bunga monokromatik.webp', '{}', 'Plakat hitam emas mewah dengan bunga monokromatik.', 70000, NULL, 'Papan Bunga', '[{"minQuantity":1,"price":70000},{"minQuantity":3,"price":68000},{"minQuantity":5,"price":65000}]'::jsonb, '1-2 hari', 5, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 42);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (1008, 'Papan Bunga - Biru Muda Mawar #PKK4', 'papan-bunga-biru-muda-mawar-pkk4', '/product-image/papan-bunga/KODE PKK4  - Plakat biru muda dengan bunga mawar di tepi.webp', '{}', 'Plakat biru muda dengan bunga mawar di tepi.', 70000, NULL, 'Papan Bunga', '[{"minQuantity":1,"price":70000},{"minQuantity":3,"price":68000},{"minQuantity":5,"price":65000}]'::jsonb, '1-2 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 43);

-- Jasa & Layanan
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (200, 'Jasa Desain', 'jasa-desain', '/product-image/design-service.svg', '{}', 'Jasa desain profesional untuk semua kebutuhan grafis Anda. Konsultasi desain gratis.', 25000, NULL, 'Jasa & Layanan', '[{"minQuantity":1,"price":25000},{"minQuantity":3,"price":22500},{"minQuantity":5,"price":20000}]'::jsonb, '1-3 hari', 4.9, true, 'design', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 44);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (2001, 'Jasa Express', 'jasa-express', '/product-image/express-service.svg', '{}', 'Layanan express untuk pengerjaan cepat dalam 24 jam.', 25000, NULL, 'Jasa & Layanan', '[{"minQuantity":1,"price":25000}]'::jsonb, '24 jam', 4.9, false, 'order', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 45);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (2002, 'Ongkir', 'ongkir', '/product-image/ongkir.svg', '{}', 'Biaya pengiriman yang dapat disesuaikan.', 0, NULL, 'Jasa & Layanan', '[{"minQuantity":1,"price":0}]'::jsonb, 'Sesuai jadwal', 4.5, false, 'order', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, true, 46);

-- Apparel
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (101, 'Gelang Tiket Kertas', 'gelang-tiket-kertas', '/product-image/New Product/GELANG-TIKET.webp', '{}', 'Gelang tiket bahan kertas untuk event, konser, dan seminar.', 1000, NULL, 'Apparel', '[{"minQuantity":1,"price":1000},{"minQuantity":3000,"price":950},{"minQuantity":5000,"price":800},{"minQuantity":7000,"price":750},{"minQuantity":9000,"price":700},{"minQuantity":20001,"price":520}]'::jsonb, '3-5 hari', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 47);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (102, 'Gelang Tiket Tissue', 'gelang-tiket-tissue', '/product-image/New Product/GELANG-TIKET-TISSUE.webp', ARRAY['/product-image/New Product/GELANG-TIKET-TISSUE-2.webp']::text[], 'Gelang tiket premium bahan tissue, nyaman dipakai. Sudah termasuk cetak, potong, dan pengunci.', 3500, NULL, 'Apparel', '[{"minQuantity":1,"price":3500},{"minQuantity":2001,"price":3000},{"minQuantity":5001,"price":2500},{"minQuantity":10001,"price":2000}]'::jsonb, '7-25 hari', 4.9, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 48);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (23, 'Sablon Kaos DTF', 'sablon-kaos-dtf', '/product-image/t-shirt-1.webp', ARRAY['/product-image/t-shirt-2.webp', '/product-image/t-shirt-3.webp']::text[], 'Sablon Kaos DTF dengan kualitas warna solid dan sablon yang elastis tidak mudah pecah. Tersedia berbagai warna kaos.', 75000, NULL, 'Apparel', '[{"minQuantity":1,"price":75000},{"minQuantity":4,"price":70000},{"minQuantity":25,"price":65000},{"minQuantity":100,"price":60000}]'::jsonb, '5-7 hari', 4.7, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 49);
insert into public.products (id, name, slug, image, additional_images, description, price, discount_price, category, price_thresholds, time, rating, bestseller, unit, is_available, pricing_method, base_price_per_sqm, min_width, max_width, min_height, max_height, models, lamination_options, is_customizable, sort_order)
values (105, 'Baju PDH', 'baju-pdh', '/product-image/Merch/baju-pdh.webp', '{}', 'Baju PDH custom berkualitas untuk keperluan organisasi/komunitas.', 120000, NULL, 'Apparel', '[{"minQuantity":1,"price":120000},{"minQuantity":51,"price":115000},{"minQuantity":100,"price":110000},{"minQuantity":300,"price":105000}]'::jsonb, '2-4 Minggu', 4.8, false, 'pcs', true, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, '[]'::jsonb, false, 50);

-- ============================================================
-- Promo Codes (from constants/index.ts)
-- ============================================================
insert into public.promo_codes (code, description, type, discount_percent, product_ids, min_quantity, override_prices, is_active)
values ('DISCOUNT10', 'Diskon 10% untuk semua produk', 'percentage', 10, NULL, NULL, NULL, true);
insert into public.promo_codes (code, description, type, discount_percent, product_ids, min_quantity, override_prices, is_active)
values ('SAVE15', 'Diskon 15% untuk semua produk', 'percentage', 15, NULL, NULL, NULL, true);
insert into public.promo_codes (code, description, type, discount_percent, product_ids, min_quantity, override_prices, is_active)
values ('PROMO20', 'Diskon 20% untuk semua produk', 'percentage', 20, NULL, NULL, NULL, true);
insert into public.promo_codes (code, description, type, discount_percent, product_ids, min_quantity, override_prices, is_active)
values ('KKN15', 'Diskon 15% untuk Paket IDC LYD 2S (min 7 pcs)', 'percentage', 15, '[8]'::jsonb, 7, NULL, true);
insert into public.promo_codes (code, description, type, discount_percent, product_ids, min_quantity, override_prices, is_active)
values ('IDCARD15', 'Diskon 15% untuk ID Card 2S', 'percentage', 15, '[2]'::jsonb, NULL, NULL, true);
insert into public.promo_codes (code, description, type, discount_percent, product_ids, min_quantity, override_prices, is_active)
values ('HUT3TH', 'Promo ulang tahun 3 tahun! Harga spesial untuk IDC LYD', 'override', 0, '[8,7]'::jsonb, NULL, '{"7":13000,"8":15000}'::jsonb, true);

-- Seed complete
